### ISSUE TITLE
Array with object access

### ISSUE THREAD

**Issue by piotrooo** [letsdrink/ouzo#170] opened 2015-01-23 22:34 UTC
I think we should have feature:

```php
$array = [
    ['id' => 123, 'name' => 'value1'],
    ['id' => 456, 'name' => 'value2']
];
$ids = Arrays::map($array, Functions::extract()->id);
```

where `$ids` returns:

```
Array
(
    [0] => 123
    [1] => 456
)
```

**Comment by piotrooo** [comment] 2015-01-24 10:19
In my opinion arrays should be treat as object, using [ArrayObject](http://php.net/manual/en/class.arrayobject.php) SPL class. This small change should work:

Objects::getValue

```php
public static function getValue($object, $field, $default = null, $accessPrivate = false)
    {
        if (is_array($object)) {
            $object = new \ArrayObject($object, \ArrayObject::ARRAY_AS_PROPS);
        }
        if (isset($object->$field)) {
            return $object->$field;
        }
        if ($accessPrivate) {
            $class = new ReflectionObject($object);
            if ($class->hasProperty($field)) {
                $property = $class->getProperty($field);
                $property->setAccessible(true);
                return $property->getValue($object);
            }
        }
        return $default;
    }
```

**Comment by piotrooo** [comment] 2015-01-24 10:31
IMO extractor should work with multidimensional array such:

```php
$array = [
    ['id' => 123, 'name' => 'value1', legs => ['leg' => 90]],
    ['id' => 456, 'name' => 'value2', legs => ['leg' => 100]]
];
$legs = Arrays::map($array, Functions::extract()->legs->leg);
```
should produces:

```
Array
(
    [0] => 90
    [1] => 100
)

```

**Comment by bbankowski** [comment] 2015-01-24 10:47
Isn't it enough to do:
```php
if (is_array($object)) {
    return Arrays::getValue($object, $field, $default);
}
```

By the way, this is duplicate of issue #166.

**Comment by piotrooo** [comment] 2015-01-24 10:53
Duplicate of #166

**Comment by piotrooo** [comment] 2015-01-24 10:56
I didn't see that #166 was closed so I reopen this.

**Closed** 2015-01-24 11:23 UTC
Labels: feature
